<a href="https://colab.research.google.com/github/YellaSrinisha/MDS_Lab/blob/main/MDS_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#installing numpy
!pip install numpy

In [3]:
#importing numpy
import numpy as np

2.0.2


In [ ]:
#numpy version
print(np.__version__)

Time taken for Python list addition (1000000 elements): 0.063303 seconds
Time taken for NumPy array addition (1000000 elements): 0.003492 seconds

NumPy is approximately 18.13 times faster for this operation.


In [118]:
import sys

# --- Python List Memory Usage ---

# Calculate memory for the Python list.
# sys.getsizeof() gives the size of the list object itself, plus some overhead.
# To get a more accurate total, we need to sum the size of each element.
python_list_memory = sys.getsizeof(python_list1) + sum(sys.getsizeof(x) for x in python_list1)
print(f"Memory taken for Python list ({size} elements): {python_list_memory / (1024*1024):.4f} MB")

# --- NumPy Array Memory Usage ---

# NumPy arrays have a convenient .nbytes attribute for total memory usage
numpy_array_memory = numpy_array1.nbytes
print(f"Memory taken for NumPy array ({size} elements): {numpy_array_memory / (1024*1024):.4f} MB")

print(f"\nNumPy array uses approximately {python_list_memory / numpy_array_memory:.2f} times less memory than Python list for this operation.")

Memory taken for Python list (1000000 elements): 34.3323 MB
Memory taken for NumPy array (1000000 elements): 7.6294 MB

NumPy array uses approximately 4.50 times less memory than Python list for this operation.


In [121]:
#creating list
my_list=[20,2,3,4,5]

In [8]:
#type of list
type(my_list)

list

In [132]:
#converting list to numpy
arr1=np.array(my_list)
print(arr1)

[[1 2]
 [3 4]]


In [11]:
#type of arr1
type(arr1)

numpy.ndarray

In [14]:
#printing dimensions
arr1.ndim

1

In [15]:
#printing datatype
arr1.dtype

dtype('int64')

In [16]:
#printing datatype name
arr1.dtype.name

'int64'

In [17]:
#printing size
arr1.size

5

In [18]:
#printing shape
arr1.shape

(5,)

In [19]:
#printing total memory
arr1.nbytes

40

In [21]:
#creating tuple and printing type
tuple=(1,2,3,4,5)
type(tuple)

tuple

In [25]:
#creating tuple with one element
tuple1=(1,)
type(tuple1)

tuple

In [27]:
#converting tuple to numpy
arr2=np.array(tuple)
print(arr2)
arr2.ndim

[1 2 3 4 5]


1

In [28]:
#printing type
type(arr2)

numpy.ndarray

In [141]:
# Create a 2x2 array from a list
my_list_2x2 = [[20, 11], [12, 13]]
array_from_list_2x2 = np.array(my_list_2x2)
print(f"2x2 Array from List:\n{array_from_list_2x2}")

2x2 Array from List:
[[20 11]
 [12 13]]


In [142]:
# Create a 2x2 array from a tuple
my_tuple_2x2 = (20, 15, 16, 17)
array_from_tuple_2x2 = np.array(my_tuple_2x2).reshape(2, 2)
print(f"\n2x2 Array from Tuple:\n{array_from_tuple_2x2}")


2x2 Array from Tuple:
[[20 15]
 [16 17]]


In [143]:
#creating list
my_list=[[20,2],[3,4]]

In [145]:
#creating matrix using list
matrix=np.array(my_list)

In [146]:
#printing matrix
print(matrix)

[[20  2]
 [ 3  4]]


In [147]:
#printing dimensions of matrix
matrix.ndim

2

In [148]:
#printig matrix shape
matrix.shape

(2, 2)

In [149]:
#flatten-returns copy of original data
matrix.flatten()

array([20,  2,  3,  4])

In [150]:
#ravel-returns view of data
matrix.ravel()

array([20,  2,  3,  4])

In [151]:
#creating array
arr4=np.array([20,2,3,4])

In [152]:
#printing array
print(arr4)

[20  2  3  4]


In [153]:
#creating2d array
arr5=np.array([[20,2],[3,4]])

In [155]:
#printing array
print(arr5)

[[20  2]
 [ 3  4]]


In [156]:
#creating 3x2 array
arr6=np.matrix([[20,2],[3,4],[5,6]])

In [157]:
##printing array
print(arr6)

[[20  2]
 [ 3  4]
 [ 5  6]]


In [158]:
#creating 1D array from 1 to 100
array_1_to_100 = np.arange(1, 101)
print(array_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [160]:
#creating 1D array of multiples of 9
arr7=np.arange(9,100,9)
print(arr7)


[ 9 18 27 36 45 54 63 72 81 90 99]


In [159]:
#creating 1D array of even numbers
arr8=np.arange(0,100,2)
print(arr8)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [161]:
#creating matrix using arange
matrix2=np.arange(0,10)
print(matrix2)

[0 1 2 3 4 5 6 7 8 9]


In [162]:
#reshape
matrix3=np.arange(0,10).reshape(2,5)
print(matrix3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [163]:
#creating 3x3 array with zeros
a=np.zeros((3,3),dtype='int')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [79]:
#printing datatype
a.dtype

dtype('int64')

In [164]:
#creating 3x3 array with zeros
b=np.ones((3,3),dtype='int')
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [165]:
#full-creating 3x3 array with a number
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [166]:
#creating 3x3 array with 20 using full
d=np.full((3,4),20)
print(d)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


In [167]:
#eye-diagonal matrix
e=np.eye(3,dtype='int')
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [103]:
#linearspace array
f=np.linspace(0,1,5)
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [102]:
#random array
g=np.random.random((3,3))
print(g)

[[0.05996691 0.15156285 0.35485261]
 [0.90403613 0.47069871 0.7532177 ]
 [0.10435872 0.94398115 0.28991449]]


In [168]:
#creating array
arr1=np.arange(20,30)
print(arr1)

[20 21 22 23 24 25 26 27 28 29]


In [107]:
#changing array element
arr1[0]=111
print(arr1[0])

111


In [169]:
#changing array elements of multiple elements at once
arr1[1:4] = [10, 11, 12]
print(arr1)

[20 10 11 12 24 25 26 27 28 29]


In [112]:
#max
arr1.max()

np.int64(111)

In [113]:
#min
arr1.min()

np.int64(2)

In [178]:
#size
arr1.size

10

In [171]:
#creating numpy from set
s={20,2,3,4,5}
arr_s=np.array(s)
print(f"Set: {s}\nNumPy Array from Set: {arr_s}")
print(type(arr_s))

Set: {2, 3, 4, 5, 20}
NumPy Array from Set: {2, 3, 4, 5, 20}
<class 'numpy.ndarray'>


In [174]:
import builtins

my_dict = {'apple': 20, 'banana': 2, 'cherry': 3}

# Create a NumPy array from dictionary keys
# Using __builtins__.list to explicitly call the built-in list constructor
array_from_dict_keys = np.array(builtins.list(my_dict.keys()))
print(f"\nNumPy Array from Dictionary Keys: {array_from_dict_keys}")

# Create a NumPy array from dictionary values
# Using __builtins__.list to explicitly call the built-in list constructor
array_from_dict_values = np.array(builtins.list(my_dict.values()))
print(f"NumPy Array from Dictionary Values: {array_from_dict_values}")

# Create a NumPy array from dictionary items (key-value pairs as tuples)
# Using __builtins__.list to explicitly call the built-in list constructor
array_from_dict_items = np.array(builtins.list(my_dict.items()))
print(f"NumPy Array from Dictionary Items:\n{array_from_dict_items}")


NumPy Array from Dictionary Keys: ['apple' 'banana' 'cherry']
NumPy Array from Dictionary Values: [20  2  3]
NumPy Array from Dictionary Items:
[['apple' '20']
 ['banana' '2']
 ['cherry' '3']]


In [177]:
# Creating a NumPy array from a string (each character as an element)
string_char = "20hello"
array_from_char = np.array(builtins.list(string_char))
print(f"Array from characters: {array_from_char}")

# Creating a NumPy array from a string (each word as an element)
string_words = "20this is a test string"
array_from_words = np.array(string_words.split(' '))
print(f"Array from words: {array_from_words}")

# Example with a string of numbers
string_numbers = "20,2,3,4,5"
array_from_numbers = np.array([int(x) for x in string_numbers.split(',')])
print(f"Array from numbers string: {array_from_numbers}")

Array from characters: ['2' '0' 'h' 'e' 'l' 'l' 'o']
Array from words: ['20this' 'is' 'a' 'test' 'string']
Array from numbers string: [20  2  3  4  5]
