<a href="https://colab.research.google.com/github/YellaSrinisha/MDS_Lab/blob/main/MDS_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#shuffle
a=np.array([20,2,3,4,5])
np.random.shuffle(a)
print(a)

[20  3  4  5  2]


In [28]:
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([20, 2, 3, 4, 5])
print("1D Array:\n", array_1d)

# Create a 2D NumPy array
array_2d = np.array([[20, 20, 30], [40, 50, 60]])
print("\n2D Array:\n", array_2d)

# --- Implement random functions ---

# Generate a 1D array of random floats between 0 and 1
random_floats_1d = np.random.rand(5)
print("\nRandom floats (1D):\n", random_floats_1d)

# Generate a 2D array of random floats between 0 and 1
random_floats_2d = np.random.rand(3, 2)
print("\nRandom floats (2D):\n", random_floats_2d)

# Generate a 1D array of random integers within a range [low, high)
# e.g., integers between 1 and 10 (exclusive of 10)
random_integers = np.random.randint(1, 10, size=7)
print("\nRandom integers (1-9):\n", random_integers)


# np.random.choice: Generate random samples from a given 1-D array
choices = ['apple', 'banana', 'cherry', 'date']
random_choice = np.random.choice(choices, size=6)
print("\nRandom choice from a list:\n", random_choice)

# np.random.shuffle: Modify a sequence in-place by shuffling its contents
list_to_shuffle = [20, 2, 3, 4, 5]
print("\nOriginal list for shuffle:\n", list_to_shuffle)
np.random.shuffle(list_to_shuffle)
print("Shuffled list (in-place):\n", list_to_shuffle)

# np.random.seed: Set a seed for reproducibility
# Setting the same seed ensures the same 'random' sequence is generated
np.random.seed(42)
seeded_random_1 = np.random.randint(0, 10, size=3) # Now generating 3 random integers
print("\nSeeded random integers (seed=42, size=3):\n", seeded_random_1)

np.random.seed(42) # Set the same seed again to demonstrate reproducibility
seeded_random_2 = np.random.randint(0,10,size=3)
print("Reproduced seeded random numbers (seed=42, rand):\n", seeded_random_2)

np.random.seed(100) # Set a different seed
different_seeded_random = np.random.randint(0, 3, size=5) # Generating an array with different seed
print("Seeded random integers (seed=100, size=5):\n", different_seeded_random)

1D Array:
 [20  2  3  4  5]

2D Array:
 [[20 20 30]
 [40 50 60]]

Random floats (1D):
 [0.27407375 0.43170418 0.94002982 0.81764938 0.33611195]

Random floats (2D):
 [[0.17541045 0.37283205]
 [0.00568851 0.25242635]
 [0.79566251 0.01525497]]

Random integers (1-9):
 [6 9 2 1 8 7 3]

Random choice from a list:
 ['apple' 'apple' 'cherry' 'banana' 'cherry' 'banana']

Original list for shuffle:
 [20, 2, 3, 4, 5]
Shuffled list (in-place):
 [4, 5, 3, 2, 20]

Seeded random integers (seed=42, size=3):
 [6 3 7]
Reproduced seeded random numbers (seed=42, rand):
 [6 3 7]
Seeded random integers (seed=100, size=5):
 [0 0 0 2 2]


In [30]:
import numpy as np

# Create a sample 2D NumPy array for demonstration
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print("Original Array:\n", arr)

# --- Indexing ---

# Access a single element (row, column)
print("\nElement at (0, 1):", arr[0, 1]) # Output: 20
print("Element at (2, 3):", arr[2, 3]) # Output: 120

# --- Slicing ---

# Get the first row (all columns of row 0)
print("\nFirst row:", arr[0, :]) # Output: [10 20 30 40]

# Get the last column (all rows of column 3)
print("Last column:\n", arr[:, 3]) # Output: [40 80 120]

# Get a sub-array (rows 0-1, columns 1-2)
# Equivalent to arr[0:2, 1:3]
sub_array = arr[:2, 1:3]
print("\nSub-array (rows 0-1, cols 1-2):\n", sub_array)

# Get all rows and a specific column
print("\nColumn 0:\n", arr[:, 0])

# Get a specific row and all columns
print("Row 1:\n", arr[1, :])

# --- Advanced Indexing (Boolean Indexing) ---
# Select elements greater than 50
greater_than_50 = arr[arr > 50]
print("\nElements greater than 50:\n", greater_than_50)

# Select rows where the first element is greater than 50
rows_filtered = arr[arr[:, 0] > 50]
print("\nRows where first element > 50:\n", rows_filtered)

# --- Advanced Indexing (Integer Array Indexing) ---
# Select specific elements using a list of coordinates
# (row_indices, col_indices)
selected_elements = arr[[0, 2], [1, 3]] # Selects (0,1) and (2,3)
print("\nElements at (0,1) and (2,3):\n", selected_elements)

# Select multiple rows in a specific order
selected_rows = arr[[2, 0]]
print("\nRows 2 and 0 (in that order):\n", selected_rows)

Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at (0, 1): 20
Element at (2, 3): 120

First row: [10 20 30 40]
Last column:
 [ 40  80 120]

Sub-array (rows 0-1, cols 1-2):
 [[20 30]
 [60 70]]

Column 0:
 [10 50 90]
Row 1:
 [50 60 70 80]

Elements greater than 50:
 [ 60  70  80  90 100 110 120]

Rows where first element > 50:
 [[ 90 100 110 120]]

Elements at (0,1) and (2,3):
 [ 20 120]

Rows 2 and 0 (in that order):
 [[ 90 100 110 120]
 [ 10  20  30  40]]


In [31]:
import numpy as np

# Create a sample 1D array for reshaping
array_1d = np.arange(12) # Array from 0 to 11
print("Original 1D Array:\n", array_1d)
print("Shape of 1D Array:", array_1d.shape)

# --- Reshaping ---

# Reshape 1D array to a 2D array (3 rows, 4 columns)
array_2d = array_1d.reshape(3, 4)
print("\nReshaped 2D Array (3x4):\n", array_2d)
print("Shape of 2D Array:", array_2d.shape)

# Reshape 1D array to a 2D array (4 rows, 3 columns)
array_2d_alt = array_1d.reshape(4, 3)
print("\nReshaped 2D Array (4x3):\n", array_2d_alt)
print("Shape of 2D Array:", array_2d_alt.shape)

# Reshape using -1 for automatic dimension calculation
# Reshape to a 2D array with 2 rows, columns calculated automatically
array_2d_auto = array_1d.reshape(2, -1)
print("\nReshaped 2D Array (2 rows, auto columns):\n", array_2d_auto)
print("Shape of 2D Array:", array_2d_auto.shape)

# Reshape to a 3D array (2x2x3)
array_3d = array_1d.reshape(2, 2, 3)
print("\nReshaped 3D Array (2x2x3):\n", array_3d)
print("Shape of 3D Array:", array_3d.shape)

# --- Flatten vs Ravel ---

# flatten() returns a copy of the array flattened into 1D
flat_copy = array_2d.flatten()
print("\nFlattened array (copy):\n", flat_copy)
print("Shape of flattened array:", flat_copy.shape)

# Modify the flattened copy
flat_copy[0] = 999
print("Original 2D Array after modifying flattened copy:\n", array_2d)
print("Modified flattened copy:\n", flat_copy)

# ravel() returns a view of the array flattened into 1D (if possible), otherwise a copy
flat_view = array_2d.ravel()
print("\nRaveled array (view):\n", flat_view)
print("Shape of raveled array:", flat_view.shape)

# Modify the raveled view
flat_view[0] = 777
print("Original 2D Array after modifying raveled view:\n", array_2d)
print("Modified raveled view:\n", flat_view)

# Demonstrate going back to 1D from 2D
back_to_1d = array_2d.reshape(-1)
print("\nBack to 1D from 2D using reshape(-1):\n", back_to_1d)
print("Shape:", back_to_1d.shape)

Original 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape of 1D Array: (12,)

Reshaped 2D Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of 2D Array: (3, 4)

Reshaped 2D Array (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape of 2D Array: (4, 3)

Reshaped 2D Array (2 rows, auto columns):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape of 2D Array: (2, 6)

Reshaped 3D Array (2x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape of 3D Array: (2, 2, 3)

Flattened array (copy):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape of flattened array: (12,)
Original 2D Array after modifying flattened copy:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modified flattened copy:
 [999   1   2   3   4   5   6   7   8   9  10  11]

Raveled array (view):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape of raveled array: (12,)
Original 2D Array after modifying raveled view:
 [[777   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
Modified raveled view

In [32]:
import numpy as np

# --- Concatenation ---
# Concatenate along an existing axis

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Concatenate along rows (axis=0)
concat_rows = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenate along rows (axis=0):\n", concat_rows)

# Concatenate along columns (axis=1)
concat_cols = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenate along columns (axis=1):\n", concat_cols)

# Concatenate 1D arrays
arr_1d_1 = np.array([1, 2, 3])
arr_1d_2 = np.array([4, 5, 6])
concat_1d = np.concatenate((arr_1d_1, arr_1d_2))
print("\nConcatenate 1D arrays:\n", concat_1d)

# --- Stacking ---
# Stacking creates new axes

# Vertical stacking (vstack) - stacks arrays in sequence vertically (row wise)
# Equivalent to concatenate(tup, axis=0)
vstack_arr = np.vstack((arr1, arr2))
print("\nVertical Stacking (vstack):\n", vstack_arr)

# Horizontal stacking (hstack) - stacks arrays in sequence horizontally (column wise)
# Equivalent to concatenate(tup, axis=1)
hstack_arr = np.hstack((arr1, arr2))
print("\nHorizontal Stacking (hstack):\n", hstack_arr)

# Stacking 1D arrays
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

vstack_1d = np.vstack((arr_a, arr_b))
print("\nVStack of 1D arrays:\n", vstack_1d)

hstack_1d = np.hstack((arr_a, arr_b))
print("\nHStack of 1D arrays:\n", hstack_1d)



Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Concatenate along rows (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate along columns (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

Concatenate 1D arrays:
 [1 2 3 4 5 6]

Vertical Stacking (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stacking (hstack):
 [[1 2 5 6]
 [3 4 7 8]]

VStack of 1D arrays:
 [[1 2 3]
 [4 5 6]]

HStack of 1D arrays:
 [1 2 3 4 5 6]

Depth Stacking (dstack):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of dstack_arr: (2, 2, 2)


In [33]:
import numpy as np

# Create sample arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
arr_float = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Array 1 (arr1):", arr1)
print("Array 2 (arr2):", arr2)
print("Float Array (arr_float):", arr_float)
print("2D Array (arr_2d):\n", arr_2d)

# --- Universal Functions (Ufuncs) ---
print("\n--- Universal Functions (Ufuncs) ---")

# Element-wise addition
add_result = np.add(arr1, arr2)
print("Element-wise Addition (arr1 + arr2):", add_result)

# Element-wise subtraction
subtract_result = np.subtract(arr1, arr2)
print("Element-wise Subtraction (arr1 - arr2):", subtract_result)

# Element-wise multiplication
multiply_result = np.multiply(arr1, arr2)
print("Element-wise Multiplication (arr1 * arr2):", multiply_result)

# Element-wise division
divide_result = np.divide(arr1, arr2)
print("Element-wise Division (arr1 / arr2):", divide_result)

# Square root
sqrt_result = np.sqrt(arr_float)
print("Square Root (np.sqrt(arr_float)):", sqrt_result)

# Exponential
exp_result = np.exp(arr_float)
print("Exponential (np.exp(arr_float)):", exp_result)

# Sine (trigonometric)
sin_result = np.sin(arr_float)
print("Sine (np.sin(arr_float)):", sin_result)

# Logarithm (natural log)
log_result = np.log(arr_float)
print("Natural Logarithm (np.log(arr_float)):", log_result)

# Power
pow_result = np.power(arr1, 2) # arr1 squared
print("Power (arr1**2):", pow_result)

# --- Mathematical Methods ---
print("\n--- Mathematical Methods ---")

# Sum of all elements
sum_all = np.sum(arr1)
print("Sum of all elements in arr1:", sum_all)

# Sum along an axis (e.g., rows for 2D array)
sum_rows = np.sum(arr_2d, axis=0)
print("Sum along columns (axis=0) in arr_2d:", sum_rows)

# Sum along an axis (e.g., columns for 2D array)
sum_cols = np.sum(arr_2d, axis=1)
print("Sum along rows (axis=1) in arr_2d:", sum_cols)

# Mean (average)
mean_arr1 = np.mean(arr1)
print("Mean of arr1:", mean_arr1)

mean_arr_2d_all = np.mean(arr_2d)
print("Mean of all elements in arr_2d:", mean_arr_2d_all)

mean_arr_2d_axis1 = np.mean(arr_2d, axis=1)
print("Mean along rows (axis=1) in arr_2d:", mean_arr_2d_axis1)

# Max value
max_arr1 = np.max(arr1)
print("Max of arr1:", max_arr1)

# Min value
min_arr1 = np.min(arr1)
print("Min of arr1:", min_arr1)

# Standard Deviation
std_arr1 = np.std(arr1)
print("Standard Deviation of arr1:", std_arr1)

# Variance
var_arr1 = np.var(arr1)
print("Variance of arr1:", var_arr1)


Array 1 (arr1): [1 2 3 4 5]
Array 2 (arr2): [5 4 3 2 1]
Float Array (arr_float): [1. 2. 3. 4. 5.]
2D Array (arr_2d):
 [[1 2 3]
 [4 5 6]]

--- Universal Functions (Ufuncs) ---
Element-wise Addition (arr1 + arr2): [6 6 6 6 6]
Element-wise Subtraction (arr1 - arr2): [-4 -2  0  2  4]
Element-wise Multiplication (arr1 * arr2): [5 8 9 8 5]
Element-wise Division (arr1 / arr2): [0.2 0.5 1.  2.  5. ]
Square Root (np.sqrt(arr_float)): [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential (np.exp(arr_float)): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine (np.sin(arr_float)): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural Logarithm (np.log(arr_float)): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Power (arr1**2): [ 1  4  9 16 25]

--- Mathematical Methods ---
Sum of all elements in arr1: 15
Sum along columns (axis=0) in arr_2d: [5 7 9]
Sum along rows (axis=1) in arr_2d: [ 6 15]
Mean of arr1: 3.0
Mean of all elements in arr

In [34]:
import numpy as np

print("--- Broadcasting Examples ---")

# Example 1: Scalar-array broadcasting
# A scalar (single number) is broadcast across an entire array.
arr_scalar = np.array([1, 2, 3, 4, 5])
scalar = 10
result_scalar_add = arr_scalar + scalar
print("\nOriginal Array (arr_scalar):", arr_scalar)
print("Scalar:", scalar)
print("Array + Scalar (result_scalar_add):", result_scalar_add)

result_scalar_mul = arr_scalar * scalar
print("Array * Scalar (result_scalar_mul):", result_scalar_mul)

# Example 2: One-dimensional array broadcasting to a two-dimensional array
# Rule 1: If the arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with ones on its left side.
# Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_1d_row = np.array([10, 20, 30]) # Shape (3,)

print("\nOriginal 2D Array (arr_2d):\n", arr_2d)
print("Original 1D Array (arr_1d_row):", arr_1d_row)

# arr_1d_row's shape (3,) becomes (1, 3) for broadcasting against (3, 3)
# Then (1, 3) is stretched to (3, 3)
result_broadcast_add_row = arr_2d + arr_1d_row
print("2D Array + 1D Row Array (result_broadcast_add_row):\n", result_broadcast_add_row)

# Example 3: Broadcasting with explicit reshaping for column-wise operation

arr_1d_col = np.array([100, 200, 300]).reshape(-1, 1) # Shape (3, 1)

print("\nOriginal 1D Column Array (arr_1d_col):\n", arr_1d_col)

# arr_1d_col's shape (3, 1) broadcasts against (3, 3)
# The (3, 1) array is stretched across the columns
result_broadcast_add_col = arr_2d + arr_1d_col
print("2D Array + 1D Column Array (result_broadcast_add_col):\n", result_broadcast_add_col)

# Example 4: Broadcasting with arrays of different shapes that are compatible

arr_a = np.array([[0, 0, 0],
                  [10, 10, 10],
                  [20, 20, 20],
                  [30, 30, 30]]) # Shape (4, 3)
arr_b = np.array([0, 1, 2]) # Shape (3,)

print("\nArray A (shape (4,3)):\n", arr_a)
print("Array B (shape (3,)):", arr_b)

# arr_b's shape (3,) becomes (1, 3) for broadcasting against (4, 3)
# Then (1, 3) is stretched to (4, 3)
result_compatible_shapes = arr_a + arr_b
print("A + B (result_compatible_shapes):\n", result_compatible_shapes)



--- Broadcasting Examples ---

Original Array (arr_scalar): [1 2 3 4 5]
Scalar: 10
Array + Scalar (result_scalar_add): [11 12 13 14 15]
Array * Scalar (result_scalar_mul): [10 20 30 40 50]

Original 2D Array (arr_2d):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Original 1D Array (arr_1d_row): [10 20 30]
2D Array + 1D Row Array (result_broadcast_add_row):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Original 1D Column Array (arr_1d_col):
 [[100]
 [200]
 [300]]
2D Array + 1D Column Array (result_broadcast_add_col):
 [[101 102 103]
 [204 205 206]
 [307 308 309]]

Array A (shape (4,3)):
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Array B (shape (3,)): [0 1 2]
A + B (result_compatible_shapes):
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [37]:
import numpy as np

print("--- Linear Algebra Examples ---")

# Create two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("\nMatrix A:\n", A)
print("Matrix B:\n", B)

# 1. Matrix Multiplication (Dot Product)
# Using np.dot() or the @ operator (Python 3.5+)
matrix_product_dot = np.dot(A, B)
matrix_product_at = A @ B
print("\n1. Matrix Multiplication (A @ B):\n", matrix_product_at)

# 2. Transpose of a Matrix
A_transpose = A.T
print("\n2. Transpose of Matrix A (A.T):\n", A_transpose)

# 3. Determinant of a Matrix
# The determinant is a scalar value that can be computed from the elements of a square matrix.
det_A = np.linalg.det(A)
print("\n3. Determinant of Matrix A (np.linalg.det(A)):", det_A)

# 4. Inverse of a Matrix
# Only square matrices can have an inverse. A matrix multiplied by its inverse yields the identity matrix.
try:
    A_inverse = np.linalg.inv(A)
    print("\n4. Inverse of Matrix A (np.linalg.inv(A)):\n", A_inverse)
    # Verify: A @ A_inverse should be close to identity matrix
    print("A @ A_inverse:\n", A @ A_inverse)
except np.linalg.LinAlgError:
    print("\n4. Inverse of Matrix A: Matrix is singular, cannot compute inverse.")


# 5. Solving Linear Equations
# Solve for x in A @ x = b
# A is a coefficient matrix, b is a dependent variable vector
A_solve = np.array([[3, 1], [1, 2]])
b_solve = np.array([9, 8])

print("\n6. Solving Linear Equations (A @ x = b)")
print("Coefficient Matrix A_solve:\n", A_solve)
print("Dependent Variable Vector b_solve:", b_solve)

x_solution = np.linalg.solve(A_solve, b_solve)
print("Solution x (np.linalg.solve(A_solve, b_solve)):", x_solution)

# Verify the solution
print("Verification (A_solve @ x_solution):", A_solve @ x_solution)

# 7. Dot product of two vectors (scalar product)
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

dot_product_vectors = np.dot(vec1, vec2)
print("\n7. Dot product of two vectors (vec1 . vec2):", dot_product_vectors)

# 8. Cross product of two vectors (only for 3D vectors)
vec3d_1 = np.array([1, 0, 0])
vec3d_2 = np.array([0, 1, 0])
cross_product = np.cross(vec3d_1, vec3d_2)
print("\n8. Cross product of two 3D vectors (vec3d_1 x vec3d_2):", cross_product)


--- Linear Algebra Examples ---

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

1. Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

2. Transpose of Matrix A (A.T):
 [[1 3]
 [2 4]]

3. Determinant of Matrix A (np.linalg.det(A)): -2.0000000000000004

4. Inverse of Matrix A (np.linalg.inv(A)):
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inverse:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

6. Solving Linear Equations (A @ x = b)
Coefficient Matrix A_solve:
 [[3 1]
 [1 2]]
Dependent Variable Vector b_solve: [9 8]
Solution x (np.linalg.solve(A_solve, b_solve)): [2. 3.]
Verification (A_solve @ x_solution): [9. 8.]

7. Dot product of two vectors (vec1 . vec2): 32

8. Cross product of two 3D vectors (vec3d_1 x vec3d_2): [0 0 1]
